package com.mysite.entity;
// Generated 18 nov. 2016 19:03:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer id;
     private String city;
     private Set courseSessions = new HashSet(0);

    public Location() {
    }

    public Location(Integer id) {
        this.id = id;
    }

    
    public Location(String city) {
        this.city = city;
    }
    public Location(String city, Set courseSessions) {
       this.city = city;
       this.courseSessions = courseSessions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Set getCourseSessions() {
        return this.courseSessions;
    }
    
    public void setCourseSessions(Set courseSessions) {
        this.courseSessions = courseSessions;
    }


    @Override
    public String toString(){
        return this.city;
    }

}


